#!/bin/sh
set -e

rm -rf ./pypack3
cp -r "$BASELOC"/o/python/cpy311-pypack3/pypack3 ./
cd pypack3

# https://docs.python.org/3.11/using/configure.html
./configure --disable-shared\
    --with-system-expat --without-system-ffi\
    --with-openssl="$COSMOS"/ssl\
    --with-tzpath=/zip/usr/share/zoneinfo\
    --prefix="$COSMOS"\
    CFLAGS="-Os -I$COSMOS/include -I$COSMOS/include/ncurses -I$COSMOS/include/uuid"

# run make and/or make install
make V=0 -s -j"$MAXPROC"
mkdir -p dummy
cp -r build/lib* ./dummy
cp ./python "$COSMOS"/bin/pypack3
