#!/bin/sh
set -e

rm -rf ./pillow
cp -r "$BASELOC"/o/python/cpy311-pillow/pillow ./
cd pillow

# https://docs.python.org/3.11/using/configure.html
./configure --disable-shared\
    --without-system-expat --without-system-ffi\
    --with-pymalloc --with-tzpath=/zip/usr/share/zoneinfo\
    --prefix="$COSMOS" CFLAGS="-Os -I$COSMOS/include -I$COSMOS/include/ncurses"

# run make and/or make install
make V=0 -s -j"$MAXPROC"
mkdir -p dummy
cp -r build/lib* ./dummy
cp ./python "$COSMOS"/bin/pillow
